name: fzf-carroarmato0
version: "0.27.0"
base: core18
summary: A command-line fuzzy finder
description: |
  fzf is a general-purpose command-line fuzzy finder.
  It's an interactive Unix filter for command-line that can be used with any list; files, command history, processes, hostnames, bookmarks, git commits, etc.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  fzf:
    command: bin/fzf
    plugs:
      - mount-observe
      - home
  fzf-tmux:
    command: bin/fzf-tmux
    plugs:
      - mount-observe
      - home

parts:
  fzf:
    plugin: make
    source: https://github.com/junegunn/fzf.git
    source-type: git
    source-tag: ${SNAPCRAFT_PROJECT_VERSION}
    build-packages:
      - golang
    override-build: |
      make
      make install
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp bin/* $SNAPCRAFT_PART_INSTALL/bin